name: slack-azz-covered-env
channels:
  - conda-forge
  - menpo
  - defaults
dependencies:
  - python=3.10.*
  - cachetools=5.3.*
  - diskcache=5.6.*
  - jinja2=3.1.*
  - slack-bolt=1.18.*
  - langchain=0.3.*
  - openai=1.*
  - faiss-cpu=1.7.*
  - tiktoken=0.8.*
  - pip=24.*
  - langchain-community=0.3.*
  - langchain-openai=0.2.*
  - cloudpickle=3.0.*
  - icecream=2.1.*
  - python-dateutil=2.9.*
  - pytest=8.1.*
  - transitions=0.9.*
  - redis=3.5.*
  - celery=5.3.*
  - fastapi
  - gunicorn
  - websockets>=12.0
  - uvicorn>=0.27.0
  - uvicorn-worker>=0.2
  - asgiref
  - environs
  - pip:
    - langchain-ollama
    - weaviate-client~=4.9
    - python-dotenv~=1.0.0
    - dependency-injector~=4.41