name: slack-azz-covered-env
channels:
  - conda-forge
  - menpo
  - defaults
dependencies:
  - python=3.10.*
  - cachetools=5.3.*
  - diskcache=5.6.*
  - jinja2=3.1.*
  - slack-bolt=1.18.*
  - langchain=0.1.*
  - openai=1.13.*
  - faiss-cpu=1.7.*
  - tiktoken=0.5.*
  - pip=24.*
  - langchain-community=0.0.*
  - cloudpickle=3.0.*
  - icecream=2.1.*
  - python-dateutil=2.9.*
  - pytest=8.1.*
  - transitions=0.9.*
  - redis=3.5.*
  - pip:
    - weaviate-client~=4.5.1
    - python-dotenv~=1.0.0
    - langchain-openai~=0.0
